[workspace]
resolver="2"

members = [
    "pool",
    "jd-server",
    "roles-utils/network-helpers",
    "roles-utils/config-helpers",
]

[profile.dev]
# Required by super_safe_lock
opt-level = 1

[profile.test]
# Required by super_safe_lock
opt-level = 1
